pekko {
  loglevel = debug

  remote.artery {
    transport = tcp
    canonical.hostname = ${clustering.ip}
    canonical.port = ${clustering.port}
  }

  cluster {
    seed-nodes = [
      "pekko://"${clustering.cluster.name}"@"${clustering.seed-ip}":"${clustering.seed-port-1},
      "pekko://"${clustering.cluster.name}"@"${clustering.seed-ip}":"${clustering.seed-port-2}
    ]
    downing-provider-class = "org.apache.pekko.cluster.sbr.SplitBrainResolverProvider"
    
    sharding {
      # The extension creates a so called coordinator that manages the distribution of shards.
      # By default it runs as a Cluster Singleton.
      # Setting this to ensure idle entities are passivated after a while to save memory.
      passivation {
        default-idle-strategy {
          idle-entity.timeout = 2 minutes
        }
      }
    }
  }

  actor {
    provider = cluster
    serialization-bindings {
      "cluster.CborSerializable" = jackson-cbor
    }
  }
}

clustering {
  ip = "127.0.0.1"
  ip = ${?CLUSTER_IP}
  port = 25251
  port = ${?CLUSTER_PORT}
  seed-ip = "127.0.0.1"
  seed-ip = ${?CLUSTER_IP}
  seed-port-1 = 25251
  seed-port-2 = 25252
  cluster.name = "ClusterSystem"
}
